#!/bin/bash

set -e
set -x

echo "Setting up dotfiles..."

# Install Homebrew
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Increase ulimit size for homebrew, the default is 1024
ulimit -n 1048576

# Install packages used for NeoVim and general terminal utilities
HOMEBREW_NO_INSTALL_CLEANUP=1 brew install fzf nvm rbenv ripgrep neovim

# Setup working directory for nvm
mkdir $HOME/.nvm

# Make ZSH the default shell
sudo chsh "$(id -un)" --shell $(which zsh)

# Copy over .config files
cp -R .config/* $HOME/.config/

# Copy over zsh files
cp .zshrc $HOME/.zshrc
cp -R .zsh $HOME/.zsh

# Copy over gitconfig files
cp .gitconfig $HOME/.gitconfig
cp .gitconfig-linux $HOME/.gitconfig-linux
